server:
  port: 9080
#  servlet:
#    context-path: /skill-tracker
####Api Gateway Configuration####
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      ###### Global Cors
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
      ##### Routes configuration#####
      routes:
        - id: auth-service
          uri: http://localhost:8080/
          predicates:
            - Path=/skill-tracker/auth/**
        - id: engineer-service
          uri: http://localhost:8081/
          predicates:
            - Path=/skill-tracker/api/v1/engineer/**
          filters:
            - ApiGatewayFilter
        - id: admin-service
          uri: http://localhost:8082/
          predicates:
            - Path=/skill-tracker/api/v1/admin/**
          filters:
            - ApiGatewayFilter
      discovery:
        locator:
          lower-case-service-id: true
#      routes:
#        - id: engineer
#          uri: http://localhost:8081
#          predicates:
#            - Path=/skill-tracker/**
#          filters:
#            - ApiGatewayFilter
#        - id: admin
#          uri: http://localhost:8082
#          predicates:
#            - Path=/skill-tracker/**
#          filters:
#            - ApiGatewayFilter
#        - id: auth
#          uri: http://localhost:8080
#          predicates:
#            - Path=/skill-tracker/auth/**
#          filters:
#            - ApiGatewayFilter

### Auth Service connection
auth-service:
  uri: http://localhost:8080/skill-tracker/auth


##Loging levels
logging:
  level:
    root: ERROR
    #core: DEBUG
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG
    org.springframework.cloud: DEBUG
    com.iiht.fse4.api.gateway: INFO

#### Actuator configuration ###
management:
  endpoint:
    health:
      show-details: "always"
  info:
    git:
      mode: "full"
  endpoints:
    web:
      exposure:
        include: "health,info,gateway"

### EUREKA ###
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/skill-tracker/eureka/

    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${random.uuid}
