version: '2'

services:
  auth-service:
    image: skilltracker/auth-service:latest
    build:
      context: .
    container_name: authservice
    depends_on:
      - postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/skill_tracker_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL=update
    ports:
      - "8080:8080"

  postgres:
    image: 'postgres:14.8-alpine'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skill_tracker_db
